### ISSUE TITLE
error in yarn deploy

### ISSUE THREAD

**Issue by vrajroham** [skyronic/vue-spa#3]
I'm getting following error on `yarn deploy`

```bash
Cloning https://github.com/******/********.git into node_modules\gh-pages\.cache
Cleaning
Fetching origin
Checking out origin/gh-pages
Removing files
Copying files
Adding all
Committing
Pushing
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': Invalid argument

error Command failed with exit code 1.
```

What would be the error?

**Comment by vrajroham** [comment]
Issue seem to be occurring on windows environment. Seems that cmd prompt was not able to take username. I was using git bash shell on windows. When I switched to Linux environment it works like charm.

**Comment by skyronic** [comment]
The deploy task is mainly to upload it to github pages skyronic.github.io/vue-spa/ :)
